# Generated by Django 4.2.3 on 2023-09-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_networkedge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkedge',
            unique_together={('from_user', 'to_user')},
        ),
    ]
