# Generated by Django 4.2.3 on 2023-09-08 09:29

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_userpost_caption_text_alter_userpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to=content.models.PostMedia.media_name),
        ),
    ]
